# Note that one can skip some hooks e.g. with `SKIP=detect-secrets git commit ...`
repos:
  - repo: local
    hooks:
      - id: Linting
        name: Style checks (ruff, isort)
        entry: sh -exc
        language: system
        always_run: true
        pass_filenames: false
        args:
          - |
            uv run --frozen isort --check paperscraper
            uv run --frozen ruff format --check paperscraper
